import { defineArrayMember, defineField, defineType } from "sanity";

export default defineType({
  name: "businessProfile",
  title: "Business Profile",
  type: "document",
  groups: [
    { name: "intro", title: "Introduction", default: true },
    { name: "credentials", title: "Credentials" },
    { name: "fleet", title: "Fleet" },
    { name: "operations", title: "Operations" },
    { name: "people", title: "Leadership" },
    { name: "clients", title: "Clients" },
    { name: "contact", title: "Contact" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Profile Title",
      type: "string",
      group: "intro",
      initialValue: "Makatu Business Enterprises",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "intro",
      initialValue: "Not your average logistics partner",
    }),
    defineField({
      name: "intro",
      title: "Company Introduction",
      type: "text",
      rows: 4,
      group: "intro",
    }),
    defineField({
      name: "heroImage",
      title: "Cover Image",
      type: "image",
      options: { hotspot: true },
      group: "intro",
    }),
    defineField({
      name: "whyChooseUs",
      title: "Why Choose Makatu",
      type: "array",
      group: "intro",
      of: [
        defineArrayMember({
          type: "object",
          name: "reason",
          fields: [
            defineField({ name: "title", title: "Title", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "description", title: "Description", type: "text", rows: 4 }),
            defineField({ name: "displayOrder", title: "Display Order", type: "number", initialValue: 0 }),
          ],
          preview: { select: { title: "title", subtitle: "description" } },
        }),
      ],
    }),
    defineField({ name: "bbbeeLevel", title: "B-BBEE Level", type: "string", group: "credentials" }),
    defineField({ name: "bbbeeSummary", title: "B-BBEE Summary", type: "text", rows: 4, group: "credentials" }),
    defineField({ name: "bbbeeCertificate", title: "Current B-BBEE Certificate", type: "file", group: "credentials" }),
    defineField({ name: "insuranceAmount", title: "Insurance Cover Headline", type: "string", group: "credentials", description: "Example: R6 million per load" }),
    defineField({ name: "insuranceSummary", title: "Insurance Summary", type: "text", rows: 4, group: "credentials" }),
    defineField({ name: "insuranceDocument", title: "Current Confirmation of Cover", type: "file", group: "credentials" }),
    defineField({ name: "dailyLocalCapacity", title: "Daily Local Vehicle Capacity", type: "number", group: "fleet" }),
    defineField({ name: "weeklyLongHaulCapacity", title: "Weekly Long-Haul Capacity", type: "string", group: "fleet", description: "Example: 20-30 vehicles" }),
    defineField({
      name: "fleet",
      title: "Fleet Types",
      type: "array",
      group: "fleet",
      of: [
        defineArrayMember({
          type: "object",
          name: "fleetItem",
          fields: [
            defineField({ name: "title", title: "Vehicle Type", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "description", title: "Capacity / Description", type: "text", rows: 3 }),
            defineField({ name: "quantity", title: "Quantity", type: "number" }),
            defineField({ name: "status", title: "Status", type: "string", initialValue: "Operational" }),
            defineField({ name: "image", title: "Photo", type: "image", options: { hotspot: true } }),
            defineField({ name: "displayOrder", title: "Display Order", type: "number", initialValue: 0 }),
          ],
          preview: { select: { title: "title", subtitle: "description", media: "image" } },
        }),
      ],
    }),
    defineField({
      name: "leadTimes",
      title: "Lead Times",
      type: "array",
      group: "operations",
      of: [
        defineArrayMember({
          type: "object",
          name: "leadTime",
          fields: [
            defineField({ name: "route", title: "Route / Delivery Type", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "collection", title: "Collection Schedule", type: "string" }),
            defineField({ name: "delivery", title: "Expected Delivery", type: "string" }),
            defineField({ name: "displayOrder", title: "Display Order", type: "number", initialValue: 0 }),
          ],
          preview: { select: { title: "route", subtitle: "delivery" } },
        }),
      ],
    }),
    defineField({
      name: "processSteps",
      title: "Delivery Process",
      type: "array",
      group: "operations",
      of: [
        defineArrayMember({
          type: "object",
          name: "processStep",
          fields: [
            defineField({ name: "title", title: "Step", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "description", title: "Description", type: "text", rows: 3 }),
            defineField({ name: "displayOrder", title: "Display Order", type: "number", initialValue: 0 }),
          ],
          preview: { select: { title: "title", subtitle: "description" } },
        }),
      ],
    }),
    defineField({ name: "operatingHours", title: "Operating Hours", type: "string", group: "operations" }),
    defineField({ name: "paymentTerms", title: "Payment Terms", type: "string", group: "operations" }),
    defineField({ name: "serviceArea", title: "Service Area", type: "text", rows: 3, group: "operations" }),
    defineField({
      name: "leadership",
      title: "Leadership Profiles",
      type: "array",
      group: "people",
      description: "Select and order the organogram employees that must appear in the profile.",
      of: [defineArrayMember({ type: "reference", to: [{ type: "organogramEmployee" }] })],
    }),
    defineField({
      name: "clients",
      title: "Clients & References",
      type: "array",
      group: "clients",
      of: [
        defineArrayMember({
          type: "object",
          name: "clientReference",
          fields: [
            defineField({ name: "name", title: "Client / Partner", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "services", title: "Services Provided", type: "text", rows: 3 }),
            defineField({ name: "contactName", title: "Reference Contact", type: "string" }),
            defineField({ name: "contactPhone", title: "Reference Phone", type: "string" }),
            defineField({ name: "logo", title: "Logo", type: "image", options: { hotspot: true } }),
            defineField({ name: "showContactPublicly", title: "Show Contact Details Publicly", type: "boolean", initialValue: false }),
            defineField({ name: "displayOrder", title: "Display Order", type: "number", initialValue: 0 }),
          ],
          preview: { select: { title: "name", subtitle: "services", media: "logo" } },
        }),
      ],
    }),
    defineField({ name: "contactHeading", title: "Closing Heading", type: "string", group: "contact", initialValue: "Let us move your business forward" }),
    defineField({ name: "contactText", title: "Closing Message", type: "text", rows: 3, group: "contact" }),
    defineField({ name: "contactEmail", title: "Email", type: "string", group: "contact" }),
    defineField({ name: "contactPhone", title: "Telephone", type: "string", group: "contact" }),
    defineField({ name: "website", title: "Website", type: "url", group: "contact" }),
    defineField({ name: "publishedAt", title: "Profile Updated Date", type: "date", group: "contact" }),
  ],
  preview: {
    select: { title: "title", subtitle: "tagline", media: "heroImage" },
  },
});
